### ISSUE TITLE
+gif :)

### ISSUE THREAD

**Issue by spacemonochrome** [deeppaz/serenes#31]
https://img.cloudygif.com/small/1ad06af15e31aebe.gif

https://i.pinimg.com/originals/28/6d/25/286d25e47f4a896359940441348d6550.gif

https://64.media.tumblr.com/734ba6db5941cd39f175f61ccf33b980/tumblr_nmvrs6ubl71qze3hdo1_r1_500.gif

https://cdn.donmai.us/original/3d/10/3d10676f5915999c2bcfd54dd96d1dd9.gif

https://i.pinimg.com/originals/44/cd/17/44cd177a82807266e2799815342de357.gif

**Comment by deeppaz** [comment]
https://github.com/deeppaz/serenes/commit/85daaca58ac21f564c791e925ede06e2d31d64e7 thanks @hasanfirat
