### ISSUE TITLE
Ses yüksekliği ayarı yapılamıyor.

### ISSUE THREAD

**Issue by spacemonochrome** [deeppaz/serenes#33]
Ses yüksekliği ayarı yapılamıyor. bug da kalmış sanırım. müzik timeline ayarlanabiliyor ama ses yüksekliği ayarlanamıyor

**Comment by spacemonochrome** [comment]
öğeyi denetle yapıp inputtan değeri 1'den 0.5'e çekince ses kısılıyor ve görselde de çubuk gösterge yarıya iniyor. ama mause ile bir müdahele yapılamıyor.

**Comment by deeppaz** [comment]
düzeldi sanırım, teşekkürler https://github.com/deeppaz/serenes/commit/900408cc4125b44dff52931503de10c450b555ce
